CREATE TABLE [dbo].[PT]
(
[PT_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[UNI_PT_KEY] [bigint] NOT NULL CONSTRAINT [DF__PT__UNI_PT_KEY__53D770D6] DEFAULT ((-1)),
[PT_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__PT__PT_TP_KEY__54CB950F] DEFAULT ((-1)),
[LGL_FORM_KEY] [bigint] NOT NULL CONSTRAINT [DF__PT__LGL_FORM_KEY__56B3DD81] DEFAULT ((-1)),
[CNTRY_KEY] [bigint] NOT NULL CONSTRAINT [DF__PT__CNTRY_KEY__589C25F3] DEFAULT ((-1)),
[BRTH_CNTRY_KEY] [bigint] NOT NULL CONSTRAINT [DF__PT__BRTH_CNTRY_K__5A846E65] DEFAULT ((-1)),
[MALE_FLAG] [smallint] NOT NULL CONSTRAINT [DF__PT__MALE_FLAG__5C6CB6D7] DEFAULT ((-1)),
[PERS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PT__PERS_ID__5E54FF49] DEFAULT ('XNA'),
[COMP_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PT__COMP_ID__5F492382] DEFAULT ('XNA'),
[FIRST_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_NAME_LAT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME_LAT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRTH_DATE] [date] NULL,
[PHONE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNT_NO] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRTH_PLACE] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RES_FLAG] [smallint] NOT NULL CONSTRAINT [DF__PT__RES_FLAG__603D47BB] DEFAULT ((-1)),
[TERR_FLAG] [smallint] NOT NULL CONSTRAINT [DF__PT__TERR_FLAG__6225902D] DEFAULT ((-1)),
[SUSP_FIN_INST_FLAG] [smallint] NOT NULL CONSTRAINT [DF__PT__SUSP_FIN_INS__640DD89F] DEFAULT ((-1)),
[OPEN_DATE] [date] NOT NULL CONSTRAINT [DF__PT__OPEN_DATE__65F62111] DEFAULT ('10000101'),
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__PT__DEL_FLAG__66EA454A] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__PT__INS_DT__68D28DBC] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__PT__UPD_DT__69C6B1F5] DEFAULT (getdate()),
[WND_DSTNC] [decimal] (18, 5) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [CK__PT__DEL_FLAG__67DE6983] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [CK__PT__MALE_FLAG__5D60DB10] CHECK (([MALE_FLAG]=(1) OR [MALE_FLAG]=(0) OR [MALE_FLAG]=((-1))))
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [CK__PT__RES_FLAG__61316BF4] CHECK (([RES_FLAG]=((-1)) OR [RES_FLAG]=(0) OR [RES_FLAG]=(1)))
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [CK__PT__SUSP_FIN_INS__6501FCD8] CHECK (([SUSP_FIN_INST_FLAG]=((-1)) OR [SUSP_FIN_INST_FLAG]=(0) OR [SUSP_FIN_INST_FLAG]=(1)))
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [CK__PT__TERR_FLAG__6319B466] CHECK (([TERR_FLAG]=((-1)) OR [TERR_FLAG]=(0) OR [TERR_FLAG]=(1)))
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [PK_PT] PRIMARY KEY CLUSTERED  ([PT_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190730-012711] ON [dbo].[PT] ([ACCOUNT_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190730-013603] ON [dbo].[PT] ([BRTH_DATE], [PHONE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190730-034629] ON [dbo].[PT] ([FIRST_NAME_LAT], [LAST_NAME_LAT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190730-012645] ON [dbo].[PT] ([PERS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [AK_PT] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190730-012748] ON [dbo].[PT] ([UNI_PT_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [FK_PT_BRTHCNTRY] FOREIGN KEY ([BRTH_CNTRY_KEY]) REFERENCES [dict].[CNTRY] ([CNTRY_KEY])
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [FK_PT_CNTRY] FOREIGN KEY ([CNTRY_KEY]) REFERENCES [dict].[CNTRY] ([CNTRY_KEY])
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [FK_PT_LGLFORM] FOREIGN KEY ([LGL_FORM_KEY]) REFERENCES [dict].[LGL_FORM] ([LGL_FORM_KEY])
GO
ALTER TABLE [dbo].[PT] ADD CONSTRAINT [FK_PT_PTTP] FOREIGN KEY ([PT_TP_KEY]) REFERENCES [dict].[PT_TP] ([PT_TP_KEY])
GO
