CREATE TABLE [dbo].[OBLG]
(
[OBLG_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_KEY] [bigint] NOT NULL,
[ISSUER_NAME] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISSUER_LGL_FORM] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLASS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNT] [bigint] NULL,
[COST_AMT] [decimal] (19, 4) NULL,
[OBLG_ORDR] [bigint] NOT NULL CONSTRAINT [DF__OBLG__OBLG_ORDR__07AC1A97] DEFAULT ((1)),
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__OBLG__DEL_FLAG__08A03ED0] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__OBLG__INS_DT__0A888742] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__OBLG__UPD_DT__0B7CAB7B] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OBLG] ADD CONSTRAINT [CK__OBLG__DEL_FLAG__09946309] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[OBLG] ADD CONSTRAINT [PK_OBLG] PRIMARY KEY CLUSTERED  ([OBLG_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OBLG] ADD CONSTRAINT [AK_OBLG] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OBLG] ADD CONSTRAINT [FK_OBLG_ITEM] FOREIGN KEY ([ITEM_KEY]) REFERENCES [dbo].[ITEM] ([ITEM_KEY])
GO
