CREATE TABLE [dbo].[INS]
(
[INS_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[ACC_TRN_KEY] [bigint] NOT NULL CONSTRAINT [DF__INS__ACC_TRN_KEY__149C0161] DEFAULT ((-1)),
[INS_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__INS__INS_TP_KEY__168449D3] DEFAULT ((-1)),
[INS_FRM_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__INS__INS_FRM_TP___186C9245] DEFAULT ((-1)),
[CCY_KEY] [bigint] NOT NULL CONSTRAINT [DF__INS__CCY_KEY__1A54DAB7] DEFAULT ((-1)),
[INS_VALID_FROM] [date] NULL,
[INS_VALID_TO] [date] NULL,
[AREA_WRLD_FLAG] [bit] NULL,
[INS_AMT] [decimal] (19, 2) NULL,
[FRANCHS_RX] [decimal] (19, 2) NULL,
[REPMT_TP_DESCR] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BASIS] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REINS_METH_CODE] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REINS_METH_NOTE] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REINS_TP_CODE] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REINS_TP_NOTE] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__INS__DEL_FLAG__1C3D2329] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__INS__INS_DT__1E256B9B] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__INS__UPD_DT__1F198FD4] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [CK__INS__DEL_FLAG__1D314762] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [PK_INS] PRIMARY KEY CLUSTERED  ([INS_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [AK_INS] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [FK_INS_ACCTRN] FOREIGN KEY ([ACC_TRN_KEY]) REFERENCES [dbo].[ACC_TRN] ([ACC_TRN_KEY])
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [FK_INS_CCY] FOREIGN KEY ([CCY_KEY]) REFERENCES [dict].[CCY] ([CCY_KEY])
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [FK_INS_INS_TP] FOREIGN KEY ([INS_TP_KEY]) REFERENCES [dict].[INS_TP] ([INS_TP_KEY])
GO
ALTER TABLE [dbo].[INS] ADD CONSTRAINT [FK_INS_INSFRMTP] FOREIGN KEY ([INS_FRM_TP_KEY]) REFERENCES [dict].[INS_FRM_TP] ([INS_FRM_TP_KEY])
GO
