CREATE TABLE [dbo].[DEAL_PT_REL]
(
[DEAL_PT_REL_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DEAL_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL_PT_R__DEAL___5A1A5A11] DEFAULT ((-1)),
[PT_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL_PT_R__PT_KE__5C02A283] DEFAULT ((-1)),
[DEAL_PT_REL_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL_PT_R__DEAL___5DEAEAF5] DEFAULT ((-1)),
[REPR_IND_FLAG] [bit] NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__DEAL_PT_R__DEL_F__5FD33367] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__DEAL_PT_R__INS_D__61BB7BD9] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__DEAL_PT_R__UPD_D__62AFA012] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL_PT_REL] ADD CONSTRAINT [CK__DEAL_PT_R__DEL_F__60C757A0] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[DEAL_PT_REL] ADD CONSTRAINT [PK_DEALPTREL] PRIMARY KEY CLUSTERED  ([DEAL_PT_REL_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL_PT_REL] ADD CONSTRAINT [AK_DEALPTREL] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL_PT_REL] ADD CONSTRAINT [FK_DEALPTREL_DEAL] FOREIGN KEY ([DEAL_KEY]) REFERENCES [dbo].[DEAL] ([DEAL_KEY])
GO
ALTER TABLE [dbo].[DEAL_PT_REL] ADD CONSTRAINT [FK_DEALPTREL_DEALPTRELTP] FOREIGN KEY ([DEAL_PT_REL_TP_KEY]) REFERENCES [dict].[DEAL_PT_REL_TP] ([DEAL_PT_REL_TP_KEY])
GO
ALTER TABLE [dbo].[DEAL_PT_REL] ADD CONSTRAINT [FK_DEALPTREL_PT] FOREIGN KEY ([PT_KEY]) REFERENCES [dbo].[PT] ([PT_KEY])
GO
