CREATE TABLE [dbo].[SUBM]
(
[SUBM_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[SUBM_TP_ID] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUBM_DATE] [datetime] NOT NULL,
[SUBM_GEN_TIMESTAMP] [datetime] NOT NULL,
[VRSN] [bigint] NOT NULL,
[OVDU_FLAG] [smallint] NOT NULL CONSTRAINT [DF__SUBM__OVDU_FLAG__67A95F59] DEFAULT ((0)),
[ACT_KIND_TP_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETAG] [datetime] NULL,
[SRC_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__SUBM__DEL_FLAG__6991A7CB] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__SUBM__INS_DT__6B79F03D] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__SUBM__UPD_DT__6C6E1476] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBM] ADD CONSTRAINT [CK__SUBM__DEL_FLAG__6A85CC04] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[SUBM] ADD CONSTRAINT [CK__SUBM__OVDU_FLAG__689D8392] CHECK (([OVDU_FLAG]=(1) OR [OVDU_FLAG]=(0) OR [OVDU_FLAG]=((-1))))
GO
ALTER TABLE [dbo].[SUBM] ADD CONSTRAINT [PK_SUBM] PRIMARY KEY CLUSTERED  ([SUBM_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBM] ADD CONSTRAINT [AK_SUBM] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
