CREATE TABLE [dbo].[ACC_TRN_PT_REL]
(
[ACC_TRN_PT_REL_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[ACC_TRN_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN_P__ACC_T__0371755F] DEFAULT ((-1)),
[PT_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN_P__PT_KE__0559BDD1] DEFAULT ((-1)),
[ACC_TRN_PT_REL_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN_P__ACC_T__07420643] DEFAULT ((-1)),
[REPR_IND_FLAG] [bit] NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__ACC_TRN_P__DEL_F__092A4EB5] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__ACC_TRN_P__INS_D__0B129727] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__ACC_TRN_P__UPD_D__0C06BB60] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRN_PT_REL] ADD CONSTRAINT [CK__ACC_TRN_P__DEL_F__0A1E72EE] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[ACC_TRN_PT_REL] ADD CONSTRAINT [PK_ACCTRNPTREL] PRIMARY KEY CLUSTERED  ([ACC_TRN_PT_REL_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRN_PT_REL] ADD CONSTRAINT [AK_ACCTRNPTREL] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRN_PT_REL] ADD CONSTRAINT [FK_ACCTRNPTREL_ACCTRN] FOREIGN KEY ([ACC_TRN_KEY]) REFERENCES [dbo].[ACC_TRN] ([ACC_TRN_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN_PT_REL] ADD CONSTRAINT [FK_ACCTRNPTREL_ACCTRNPTRELTP] FOREIGN KEY ([ACC_TRN_PT_REL_TP_KEY]) REFERENCES [dict].[ACC_TRN_PT_REL_TP] ([ACC_TRN_PT_REL_TP_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN_PT_REL] ADD CONSTRAINT [FK_ACCTRNPTREL_PT] FOREIGN KEY ([PT_KEY]) REFERENCES [dbo].[PT] ([PT_KEY])
GO
