CREATE TABLE [dbo].[ITEM]
(
[ITEM_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DEAL_KEY] [bigint] NOT NULL,
[ITEM_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__ITEM__ITEM_TP_KE__3C54ED00] DEFAULT ((-1)),
[ITEM_SUB_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__ITEM__ITEM_SUB_T__3E3D3572] DEFAULT ((-1)),
[BAR_CODE] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCY_KEY] [bigint] NOT NULL CONSTRAINT [DF__ITEM__CCY_KEY__40257DE4] DEFAULT ((-1)),
[ACT_TP_DESCR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACT_DESCR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMT] [decimal] (19, 4) NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__ITEM__DEL_FLAG__420DC656] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__ITEM__INS_DT__43F60EC8] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__ITEM__UPD_DT__44EA3301] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [CK__ITEM__DEL_FLAG__4301EA8F] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED  ([ITEM_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [AK_ITEM] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [FK_ITEM_CCY] FOREIGN KEY ([CCY_KEY]) REFERENCES [dict].[CCY] ([CCY_KEY])
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [FK_ITEM_DEAL] FOREIGN KEY ([DEAL_KEY]) REFERENCES [dbo].[DEAL] ([DEAL_KEY])
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [FK_ITEM_ITEMSUBTP] FOREIGN KEY ([ITEM_SUB_TP_KEY]) REFERENCES [dict].[ITEM_SUB_TP] ([ITEM_SUB_TP_KEY])
GO
ALTER TABLE [dbo].[ITEM] ADD CONSTRAINT [FK_ITEM_ITEMTP] FOREIGN KEY ([ITEM_TP_KEY]) REFERENCES [dict].[ITEM_TP] ([ITEM_TP_KEY])
GO
