CREATE TABLE [dbo].[REAL_EST]
(
[REAL_EST_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_KEY] [bigint] NOT NULL,
[REAL_EST_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__REAL_EST__REAL_E__4A6E022D] DEFAULT ((-1)),
[CADASTRAL_NUMBER] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__CADAST__4C564A9F] DEFAULT ('XNA'),
[REG_NUMBER] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__REG_NU__4D4A6ED8] DEFAULT ('XNA'),
[REAL_EST_TP_DESCR] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__REAL_E__4E3E9311] DEFAULT ('XNA'),
[REAL_EST_SUB_TP_DESCR] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__REAL_E__4F32B74A] DEFAULT ('XNA'),
[OWN_TP_DESCR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__OWN_TP__5026DB83] DEFAULT ('XNA'),
[ENTRANCE_NUMBER] [bigint] NULL,
[FLOOR_NUMBER] [bigint] NULL,
[FLAT_NUMBER] [bigint] NULL,
[FLAT_AREA] [decimal] (19, 2) NULL,
[ADDR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__ADDR__511AFFBC] DEFAULT ('XNA'),
[DESCR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__DESCR__520F23F5] DEFAULT ('XNA'),
[LOC_DESCR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__LOC_DE__5303482E] DEFAULT ('XNA'),
[TP_ID] [smallint] NULL,
[PART_NUMERATOR] [decimal] (19, 2) NULL,
[PART_DENOMINATOR] [decimal] (19, 2) NULL,
[STAT_DESCR] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REAL_EST__STAT_D__53F76C67] DEFAULT ('XNA'),
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__REAL_EST__DEL_FL__54EB90A0] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__REAL_EST__INS_DT__56D3D912] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__REAL_EST__UPD_DT__57C7FD4B] DEFAULT (getdate()),
[MEASURED_AREA] [decimal] (19, 2) NULL,
[DOCUMENTED_AREA] [decimal] (19, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REAL_EST] ADD CONSTRAINT [CK__REAL_EST__DEL_FL__55DFB4D9] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[REAL_EST] ADD CONSTRAINT [PK_REALEST] PRIMARY KEY CLUSTERED  ([REAL_EST_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REAL_EST] ADD CONSTRAINT [AK_REALEST] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REAL_EST] ADD CONSTRAINT [FK_REALEST_ITEM] FOREIGN KEY ([ITEM_KEY]) REFERENCES [dbo].[ITEM] ([ITEM_KEY])
GO
ALTER TABLE [dbo].[REAL_EST] ADD CONSTRAINT [FK_REALEST_REALESTTP] FOREIGN KEY ([REAL_EST_TP_KEY]) REFERENCES [dict].[REAL_EST_TP] ([REAL_EST_TP_KEY])
GO
