CREATE TABLE [dbo].[ACC_TRN]
(
[ACC_TRN_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[SUBM_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__SUBM_KE__5C57A83E] DEFAULT ((-1)),
[ACC_TRN_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__ACC_TRN__5E3FF0B0] DEFAULT ((-1)),
[CCY_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__CCY_KEY__60283922] DEFAULT ((-1)),
[SRC_CNTRY_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__SRC_CNT__62108194] DEFAULT ((-1)),
[TRG_CNTRY_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__TRG_CNT__63F8CA06] DEFAULT ((-1)),
[INS_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__INS_TP___65E11278] DEFAULT ((-1)),
[GMBLNG_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__ACC_TRN__GMBLNG___67C95AEA] DEFAULT ((-1)),
[MAIN_ACC_TRN_FLAG] [bit] NOT NULL,
[REFERENCE] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACC_TRN_DATE] [datetime] NULL,
[ACC_TRN_AMT] [decimal] (19, 4) NULL,
[CASH_FLAG] [bit] NULL,
[ACC_TRN_PURP] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACC_TRN_LOC] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACC_TRN_PLC] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENSION] [xml] NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__ACC_TRN__DEL_FLA__69B1A35C] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__ACC_TRN__INS_DT__6B99EBCE] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__ACC_TRN__UPD_DT__6C8E1007] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [CK__ACC_TRN__DEL_FLA__6AA5C795] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [PK_ACCTRN] PRIMARY KEY CLUSTERED  ([ACC_TRN_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [AK_ACCTRN] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_CCY] FOREIGN KEY ([CCY_KEY]) REFERENCES [dict].[CCY] ([CCY_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_DEALTP] FOREIGN KEY ([ACC_TRN_TP_KEY]) REFERENCES [dict].[ACC_TRN_TP] ([ACC_TRN_TP_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_GMBLNGTP] FOREIGN KEY ([GMBLNG_TP_KEY]) REFERENCES [dict].[GMBLNG_TP] ([GMBLNG_TP_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_INSTP] FOREIGN KEY ([INS_TP_KEY]) REFERENCES [dict].[INS_TP] ([INS_TP_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_SRCCNTRY] FOREIGN KEY ([SRC_CNTRY_KEY]) REFERENCES [dict].[CNTRY] ([CNTRY_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_SUBM] FOREIGN KEY ([SUBM_KEY]) REFERENCES [dbo].[SUBM] ([SUBM_KEY])
GO
ALTER TABLE [dbo].[ACC_TRN] ADD CONSTRAINT [FK_ACCTRN_TRGCNTRY] FOREIGN KEY ([TRG_CNTRY_KEY]) REFERENCES [dict].[CNTRY] ([CNTRY_KEY])
GO
