CREATE TABLE [dbo].[DEAL]
(
[DEAL_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[SUBM_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL__SUBM_KEY__35DCF99B] DEFAULT ((-1)),
[DEAL_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL__DEAL_TP_KE__37C5420D] DEFAULT ((-1)),
[CNTRY_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL__CNTRY_KEY__39AD8A7F] DEFAULT ((-1)),
[DEAL_STAT_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL__DEAL_STAT___3B95D2F1] DEFAULT ((-1)),
[DEAL_FRM_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL__DEAL_FRM_K__3D7E1B63] DEFAULT ((-1)),
[CCY_KEY] [bigint] NOT NULL CONSTRAINT [DF__DEAL__CCY_KEY__3F6663D5] DEFAULT ((-1)),
[MAIN_DEAL_FLAG] [bit] NOT NULL,
[REFERENCE] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEAL_DATE] [datetime] NULL,
[DEAL_AMT] [decimal] (19, 4) NULL,
[DEAL_PURP] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEAL_LOC] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEAL_SUBJ] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEAL_START_DATE] [datetime] NULL,
[DEAL_END_DATE] [datetime] NULL,
[REG_ISSUER] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REG_DATE] [datetime] NULL,
[REG_NO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EXTENSION] [xml] NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__DEAL__DEL_FLAG__414EAC47] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__DEAL__INS_DT__4336F4B9] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__DEAL__UPD_DT__442B18F2] DEFAULT (getdate()),
[STOCK_FLAG] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [CK__DEAL__DEL_FLAG__4242D080] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [PK_DEAL] PRIMARY KEY CLUSTERED  ([DEAL_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [AK_DEAL] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [FK_DEAL_CCY] FOREIGN KEY ([CCY_KEY]) REFERENCES [dict].[CCY] ([CCY_KEY])
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [FK_DEAL_CNTRY] FOREIGN KEY ([CNTRY_KEY]) REFERENCES [dict].[CNTRY] ([CNTRY_KEY])
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [FK_DEAL_DEALFRM] FOREIGN KEY ([DEAL_FRM_KEY]) REFERENCES [dict].[DEAL_FRM] ([DEAL_FRM_KEY])
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [FK_DEAL_DEALSTAT] FOREIGN KEY ([DEAL_STAT_KEY]) REFERENCES [dict].[DEAL_STAT] ([DEAL_STAT_KEY])
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [FK_DEAL_DEALTP] FOREIGN KEY ([DEAL_TP_KEY]) REFERENCES [dict].[DEAL_TP] ([DEAL_TP_KEY])
GO
ALTER TABLE [dbo].[DEAL] ADD CONSTRAINT [FK_DEAL_SUBM] FOREIGN KEY ([SUBM_KEY]) REFERENCES [dbo].[SUBM] ([SUBM_KEY])
GO
