CREATE TABLE [dbo].[SUBM_PT_REL]
(
[SUBM_PT_REL_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[SUBM_KEY] [bigint] NOT NULL CONSTRAINT [DF__SUBM_PT_R__SUBM___72E607DB] DEFAULT ((-1)),
[PT_KEY] [bigint] NOT NULL CONSTRAINT [DF__SUBM_PT_R__PT_KE__74CE504D] DEFAULT ((-1)),
[SUBM_PT_REL_TP_KEY] [bigint] NOT NULL CONSTRAINT [DF__SUBM_PT_R__SUBM___76B698BF] DEFAULT ((-1)),
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEL_FLAG] [smallint] NOT NULL CONSTRAINT [DF__SUBM_PT_R__DEL_F__789EE131] DEFAULT ((0)),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__SUBM_PT_R__INS_D__7A8729A3] DEFAULT (getdate()),
[UPD_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__SUBM_PT_R__UPD_D__7B7B4DDC] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBM_PT_REL] ADD CONSTRAINT [CK__SUBM_PT_R__DEL_F__7993056A] CHECK (([DEL_FLAG]=(0) OR [DEL_FLAG]=(1)))
GO
ALTER TABLE [dbo].[SUBM_PT_REL] ADD CONSTRAINT [PK_SUBMPTREL] PRIMARY KEY CLUSTERED  ([SUBM_PT_REL_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBM_PT_REL] ADD CONSTRAINT [AK_SUBMPTREL] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBM_PT_REL] ADD CONSTRAINT [FK_DEALPTREL_SUBM] FOREIGN KEY ([SUBM_KEY]) REFERENCES [dbo].[SUBM] ([SUBM_KEY])
GO
ALTER TABLE [dbo].[SUBM_PT_REL] ADD CONSTRAINT [FK_SUBMPTREL_PT] FOREIGN KEY ([PT_KEY]) REFERENCES [dbo].[PT] ([PT_KEY])
GO
ALTER TABLE [dbo].[SUBM_PT_REL] ADD CONSTRAINT [FK_SUBMPTREL_SUBMPTRELTP] FOREIGN KEY ([SUBM_PT_REL_TP_KEY]) REFERENCES [dict].[SUBM_PT_REL_TP] ([SUBM_PT_REL_TP_KEY])
GO
