CREATE TABLE [dict].[CNTRY]
(
[CNTRY_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[CCY_KEY] [bigint] NOT NULL,
[DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMBARGO_FLAG] [bit] NOT NULL CONSTRAINT [DF__CNTRY__EMBARGO_F__32E0915F] DEFAULT ((0)),
[EU_FLAG] [bit] NOT NULL CONSTRAINT [DF__CNTRY__EU_FLAG__34C8D9D1] DEFAULT ((0)),
[ISO_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RISK_FLAG] [bigint] NOT NULL CONSTRAINT [DF__CNTRY__RISK_FLAG__36B12243] DEFAULT ((0)),
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__CNTRY__INS_DT__38996AB5] DEFAULT (getdate()),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__CNTRY__UPD_DT__398D8EEE] DEFAULT (getdate()),
[UPD_PROCESS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dict].[CNTRY] ADD CONSTRAINT [CK__CNTRY__EMBARGO_F__33D4B598] CHECK (([EMBARGO_FLAG]=(0) OR [EMBARGO_FLAG]=(1)))
GO
ALTER TABLE [dict].[CNTRY] ADD CONSTRAINT [CK__CNTRY__EU_FLAG__35BCFE0A] CHECK (([EU_FLAG]=(0) OR [EU_FLAG]=(1)))
GO
ALTER TABLE [dict].[CNTRY] ADD CONSTRAINT [CK__CNTRY__RISK_FLAG__37A5467C] CHECK (([RISK_FLAG]=(0) OR [RISK_FLAG]=(1)))
GO
ALTER TABLE [dict].[CNTRY] ADD CONSTRAINT [PK_CNTRY] PRIMARY KEY CLUSTERED  ([CNTRY_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dict].[CNTRY] ADD CONSTRAINT [AK_CNTRY] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dict].[CNTRY] ADD CONSTRAINT [FK_CNTRY_CCY] FOREIGN KEY ([CCY_KEY]) REFERENCES [dict].[CCY] ([CCY_KEY])
GO
