CREATE TABLE [dict].[ID_CARD_TP]
(
[ID_CARD_TP_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__ID_CARD_T__INS_D__6D9742D9] DEFAULT (getdate()),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__ID_CARD_T__UPD_D__6E8B6712] DEFAULT (getdate()),
[UPD_PROCESS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dict].[ID_CARD_TP] ADD CONSTRAINT [PK_IDCARDTPKEY] PRIMARY KEY CLUSTERED  ([ID_CARD_TP_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dict].[ID_CARD_TP] ADD CONSTRAINT [AK_IDCARDTPKEY] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
