CREATE TABLE [dict].[ITEM_TP]
(
[ITEM_TP_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__ITEM_TP__INS_DT__05F8DC4F] DEFAULT (getdate()),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__ITEM_TP__UPD_DT__06ED0088] DEFAULT (getdate()),
[UPD_PROCESS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dict].[ITEM_TP] ADD CONSTRAINT [PK_ITEMTP] PRIMARY KEY CLUSTERED  ([ITEM_TP_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dict].[ITEM_TP] ADD CONSTRAINT [AK_ITEMTP] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
