CREATE TABLE [dict].[SUBM_PT_REL_TP]
(
[SUBM_PT_REL_TP_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__SUBM_PT_R__INS_D__668030F6] DEFAULT (getdate()),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__SUBM_PT_R__UPD_D__6774552F] DEFAULT (getdate()),
[UPD_PROCESS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dict].[SUBM_PT_REL_TP] ADD CONSTRAINT [PK_SUBMPTRELTP] PRIMARY KEY CLUSTERED  ([SUBM_PT_REL_TP_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dict].[SUBM_PT_REL_TP] ADD CONSTRAINT [AK_SUBMPTRELTP] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
