CREATE TABLE [dict].[ACC_TRN_TP]
(
[ACC_TRN_TP_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__ACC_TRN_T__INS_D__11007AA7] DEFAULT (getdate()),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__ACC_TRN_T__UPD_D__11F49EE0] DEFAULT (getdate()),
[UPD_PROCESS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_FLAG] [bit] NOT NULL CONSTRAINT [DF__ACC_TRN_T__INS_F__200DB40D] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dict].[ACC_TRN_TP] ADD CONSTRAINT [PK_ACCTRNTP] PRIMARY KEY CLUSTERED  ([ACC_TRN_TP_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dict].[ACC_TRN_TP] ADD CONSTRAINT [AK_ACCTRNTP] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
