CREATE TABLE [dict].[DEAL_TP]
(
[DEAL_TP_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOC_DESCR] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SRC_SYS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INS_DT] [datetime] NOT NULL CONSTRAINT [DF__DEAL_TP__INS_DT__7226EDCC] DEFAULT (getdate()),
[INS_PROCESS_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPD_DT] [datetime] NOT NULL CONSTRAINT [DF__DEAL_TP__UPD_DT__731B1205] DEFAULT (getdate()),
[UPD_PROCESS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OBLG_EXTNSN_FLAG] [bit] NOT NULL CONSTRAINT [DF__DEAL_TP__OBLG_EX__116A8EFB] DEFAULT ((0)),
[REAL_EST_EXTNSN_FLAG] [bit] NOT NULL CONSTRAINT [DF__DEAL_TP__REAL_ES__125EB334] DEFAULT ((0)),
[FLT_EXTNSN_FLAG] [bit] NOT NULL CONSTRAINT [DF__DEAL_TP__FLT_EXT__30AE302A] DEFAULT ((0)),
[PLC_EXTNSN_FLAG] [bit] NOT NULL CONSTRAINT [DF__DEAL_TP__PLC_EXT__31A25463] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dict].[DEAL_TP] ADD CONSTRAINT [PK_DEALTP] PRIMARY KEY CLUSTERED  ([DEAL_TP_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dict].[DEAL_TP] ADD CONSTRAINT [AK_DEALTP] UNIQUE NONCLUSTERED  ([SRC_ID], [SRC_SYS_ID]) ON [PRIMARY]
GO
