CREATE TABLE [jobs].[JOBS_LOG_SEQ]
(
[ETL_LOG_SEQ_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[SEQ_GEN_DATE] [datetime] NOT NULL CONSTRAINT [DF__JOBS_LOG___SEQ_G__26CFC035] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [jobs].[JOBS_LOG_SEQ] ADD CONSTRAINT [PK__JOBS_LOG__98F6E51C24E777C3] PRIMARY KEY CLUSTERED  ([ETL_LOG_SEQ_KEY]) ON [PRIMARY]
GO
