CREATE TABLE [jobs].[ETL_LOG]
(
[ETL_LOG_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[ETL_START_DATE] [datetime] NULL,
[ETL_END_DATE] [datetime] NULL,
[ETL_NAME] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P_DONOR_ID] [bigint] NULL,
[P_SUMBISSION_ID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P_JOB_ID] [bigint] NULL,
[P_EXTENSION] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_STAT] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROW_COUNT] [bigint] NULL,
[ERROR_LOG] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [jobs].[ETL_LOG] ADD CONSTRAINT [PK__ETL_LOG__E1C335BB351DDF8C] PRIMARY KEY CLUSTERED  ([ETL_LOG_KEY]) ON [PRIMARY]
GO
