CREATE TABLE [jobs].[ETL_LOG_STEP]
(
[ETL_LOG_STEP_KEY] [bigint] NOT NULL IDENTITY(1, 1),
[ETL_LOG_KEY] [bigint] NULL,
[LOG_DATE] [datetime] NULL,
[LOG_NAME] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_DATA] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [jobs].[ETL_LOG_STEP] ADD CONSTRAINT [PK__ETL_LOG___4860C38D4FD1D5C8] PRIMARY KEY CLUSTERED  ([ETL_LOG_STEP_KEY]) ON [PRIMARY]
GO
ALTER TABLE [jobs].[ETL_LOG_STEP] ADD CONSTRAINT [FK_ETLLOGSTEP_ETLLOG] FOREIGN KEY ([ETL_LOG_KEY]) REFERENCES [jobs].[ETL_LOG] ([ETL_LOG_KEY])
GO
